version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    container_name: cuck_postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./docker/data/postgres:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: postgres
